//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR5.AppDataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductArticleNumber { get; set; }
        public int ProductNameId { get; set; }
        public string ProductDescription { get; set; }
        public int ProductCategoryId { get; set; }
        public int ProductManufacturerId { get; set; }
        public int ProductCost { get; set; }
        public Nullable<int> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public int ProductStatusId { get; set; }
        public string ProductPhoto { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductManufacturer ProductManufacturer { get; set; }
        public virtual ProductName ProductName { get; set; }
        public virtual ProductStatus ProductStatus { get; set; }

        public string StrProductCost
        {
            get => ProductCost.ToString();

            set { }
        }
        public string StrProductManufacture
        {
            get => ProductManufacturerId.ToString();
            set { }
        }
        public string StrProductCategory
        {
            get => ProductCategory.ToString();
            set { }
        }

        public string StrProductName
        { get => ProductName.ToString(); 
            
            set { }
            
        }
        
    }
}
